server:
  port: 8081

spring:
  application:
    name: employee

    datasource:
      url: jdbc:h2:mem:employee_db
      username: sa
      password: sa
      driverClassName: org.h2.Driver
      jpa:
        spring.jpa.database-platform: org.hibernate.dialect.H2Dialect