server:
  port: 8081

spring:
  profiles:
    active: "dev"
  application:
    name: time-tracker

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:employee_db
    username: sa
    password: sa
    driverClassName: org.h2.Driver
    jpa:
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

springdoc:
  swagger-ui:
    operations-sorter: method